Add Kubernetes attributes table & update example
NetAppDocs/trident pull request #79
Opened 2022-02-08 16:18 UTC by juliantap

Add attributes to Kubernetes attributes table & updated YAML example to close #76

2022-02-08 18:58 UTC, balaramesh requested changes

2022-02-08 18:58 UTC, balaramesh commented on trident-reference/objects.adoc
> +|allowVolumeExpansion |boolean |true, false |Enable or disable support for growing the PVC size |ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san, aws-cvs, gcp-cvs, azure-n
Version must be 1.11+

2022-02-08 18:58 UTC, balaramesh commented on trident-reference/objects.adoc
> +|volumeBindingMode |string |Immediate, WaitForFirstConsumer |Choose when volume binding and dynamic provisioning occurs |ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san, a
Version must be 1.17+ here

2022-02-09 15:37 UTC, juliantap commented on trident-reference/objects.adoc
> +|volumeBindingMode |string |Immediate, WaitForFirstConsumer |Choose when volume binding and dynamic provisioning occurs |ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san, a
Done! Thanks! I'll merge now @balaramesh

2022-02-09 15:48 UTC, balaramesh approved these changes
Thanks! LGTM

2022-02-09 15:51 UTC, merged